#!/bin/bash

if [ $# -eq 0 ]
    then
    echo "ERROR: You must provide at leats the path to vauxoo ansible files"
    exit
fi


PARAMS=""

for i in "$@"
do
case $i in
    -k | --ask-pass)
        PARAMS="$PARAMS --ask-pass"
    ;;
    -K | --ask-sudo-pass)
        PARAMS="$PARAMS --ask-sudo-pass"
    ;;
    --travis)
        PARAMS="$PARAMS --connection=local --sudo -vvvv"
    ;;
    *)
            # unknown option
        if [ -d $i ]
            then
            ANSIBLE_PATH=$i
        fi
    ;;
esac
done

if [ ! -d $ANSIBLE_PATH ]
    then
    echo "ERROR: Path '$1' does not exists"
    exit
fi

ANSIBLE_FOLDER="$(pwd)"
TMP="$(dirname "$ANSIBLE_FOLDER")"
APP_FOLDER="$(dirname "$TMP")"

if [ ! -d $APP_FOLDER ]
    then
    echo "ERROR: The app folder you specified '$APP_FOLDER' does not exists"
    exit
fi

if [ ! -e $ANSIBLE_PATH/site.yml ]
    then
    echo "ERROR: Playbook file '$ANSIBLE_PATH/site.yml' does not exists"
    exit
fi

if [ ! -e $ANSIBLE_FOLDER/inventory ]
    then
    echo "ERROR: Inventory file '$ANSIBLE_FOLDER/inventory' does not exists"
    exit
fi

if [ ! -e $ANSIBLE_FOLDER/vars.yml ]
    then
    echo "ERROR: The vars file '$ANSIBLE_FOLDER/vars.yml' does not exists"
    exit
fi

ansible-playbook $ANSIBLE_PATH/site.yml -i $ANSIBLE_FOLDER/inventory --extra-vars "app_module=$APP_FOLDER host=localhost" $PARAMS
