---
- name: Check data and logs folder
  file:
    path: "{{ item }}"
    state: directory
    group: "{{ user }}"
    mode: 0774
    recurse: yes
  sudo: yes
  with_items:
    - "{{ data_path }}/logs/odoo"
    - "{{ data_path }}/logs/postgres"
    - "{{ data_path }}/data/postgres_data"
    - "{{ data_path }}/data/postgres_config"
    - "{{ data_path }}/data/redis_data"
