#!/bin/bash

# vauxoo com packages
# empty

# addons-vauxoo packages #FIXME: This modules make error use or not use it
sudo pip install recaptcha-client egenix-mx-base

# odoo default packages without depend in setup.py
sudo pip install PyWebDAV mygengo
sudo apt-get install pdftotext antiword

#webkit patched process #FIXME: Fix modules to use new webkit version
mkdir -p /tmp/webkit_patched
wget -O /tmp/webkit_patched/wkhtmltopdf.tar.bz2 https://wkhtmltopdf.googlecode.com/files/wkhtmltopdf-0.11.0_rc1-static-amd64.tar.bz2
bzip2 -dc /tmp/webkit_patched/wkhtmltopdf.tar.bz2 | tar -xvO >/tmp/webkit_patched/webkit-patched
sudo cp /tmp/webkit_patched/webkit-patched /usr/bin/wkhtmltopdf

exit 0
